version: '3.3'
services:
  prod:
    container_name: uniqlo_server_prod
    image: uniqlo-server-prod:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ${PWD}/.env:/app/.env
    network_mode: host
    restart: unless-stopped